name: Set My Github Status

on: [push]

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set My Github Status
        uses: ./
        env:
          STEAM_USER_ID: "76561197984170060"
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          


      