name: Set My Github Status From Steam

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

jobs:

  set-status:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2
      - name: Set My Github Status From Steam
        # To test the action on the repo itself, use: ./
        uses: mendhak/steam-github-profile-status@v1.1  
        env:
          STEAM_USER_ID: "76561197984170060"
          GITHUB_ACCESS_TOKEN: "${{ secrets.MY_GITHUB_ACCESS_TOKEN }}"
          

      
